version: '3.1'

services:
  api:
    build: .
    ports:
      - '8000:8000'

  database:
    container_name: postgres
    image: postgres:16.1-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    command: -c fsync=off

  cache:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
